

services:
  server:
    build:
      context: .
      target: dev
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
    env_file:
      - .env
    volumes:
      - ./certs:/usr/src/app/certs
      - ./logs:/usr/src/app/logs
  
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    
      - "15672:15672"  
    environment:
      - RABBITMQ_DEFAULT_USER=guest     
      - RABBITMQ_DEFAULT_PASS=guest     
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 
    networks:
      - app-network
    healthcheck:     
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  
networks:
  app-network:
    driver: bridge

volumes:
  rabbitmq_data:
