name: CI/CD

on:
  push:
    branches:
      - develop

# env:
#   REGISTRY: ${{ secrets.REGISTRY }}
#   REGISTRY_NAMESPACE: ${{ secrets.SCW_NAMESPACE }}
#   IMAGE_NAME: ${{ github.event.repository.name }}



jobs:
# Décommentez pas ça, la config TS fait n'importe quoi
  # eslint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 22.13
  #         cache: 'npm'
  #     - run: npm ci
  #     - run: npm run lint
  #       name: Run ESLint
  
  build-ts:
    runs-on: ubuntu-latest
    needs: eslint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.13
          cache: 'npm'
      - run: npm ci
      - run: npm run build
        name: Build TypeScript